package com.teoco.rnto.util.enums;

/**
 * Enumeration of fields generated by Ericsson research parser
 */
public enum EricssonMessageField {
    LEN,
    TYPE,
    EVENT_ID,
    TIME_IN_MS,
    HH,
    MM,
    SS,
    MSEC,
    SCANNER,
    RBS_MODULE,
    CID,
    ENB,
    CELL,
    ENBS1APID,
    MMES1APID,
    GUMMEI,
    RAC_UE_REF,
    TRACE_RECORDING_SESSION_REF,
    DIRECTION,
    MESSAGE
}
